//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string ISBN { get; set; }
        public int PublisherId { get; set; }
        public int AuthorId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<int> Edition { get; set; }
        public Nullable<double> AverageRating { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
